### ISSUE TITLE
Convert the search criteria to a readable form

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-search-print#11]
Create the `SearchCriteriaFactory` helper object. The Create method takes an instance of `ClinicalTrialAPIClient` and processes the request body to return an instance of `SearchCriteria` containing the various search criteria in a format which can be used for display on the rendered page.

**Parent Issue:** #8 

### Sub-Tasks
- [ ] Create the `SearchCriteriaFactory` class
- [ ] Create the `SearchCriteria` class
- [ ] Implement Unit Tests

**Comment by blairlearn** [comment]
Rolled into #21
