### ISSUE TITLE
Import NCILibrary.Core and NCILibrary.DataManager projects

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-search-print#17]
In order to leverage existing code, we need to import some of the NCILibrary projects.

**Parent Issue:** #16 

### Sub-Tasks
- [ ] Copy the projects into print service solution
- [ ] Update the project files to v4.6.1 of the .Net framework
- [ ] Resolve the outstanding compiler warning messages.

**Comment by blairlearn** [comment]
## Warning resolution in NCILibrary.Core.
- Remove NCI.Messaging namespace 
  - MSMQReceiver.cs
  - MSMQSender.cs
  - NCIMessagingException
- XmlStrings.cs
  - remove unreachable code in `ToInt(XmlNode node, int defValue, bool throwError)`.
  - remove unreachable code in `ToUInt(XmlNode node, uint defValue, bool throwError)`.
  - remove unreachable code in `ToLong(XmlNode node, long defValue, bool throwError)`.
  - remove unreachable code in `ToGuid(XmlNode node, Guid defValue, bool throwError)`.
- NciUrl - remove unused variable `_isCaseInsensitive`.

## Warning resolution in NCILibrary.DataManager.
- BlogSearchDataManager - Add unused exception variable to log exception details.
- SearchDataManager - Remove unused exception variable on swallowed exceptions.
