### ISSUE TITLE
Enabler: Add Integration Tests

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-search-print#87]
# Add Integration tests

The system currently lacks any end-to-end tests aside from a few for bad inputs.

Using the live API is undesirable as the data changes daily. To work around this, we can create a mock API (Node with Express?) backed by a small number of static files containing trial data as returned by the current API. At present, only the `/trials` endpoint needs to be mocked.

SQL Server (for storing printable pages) may also present some challenges.

> **ESTIMATE** TBD

### Resources:

- [Running SQL Server in a container on Github Actions](https://datastation.multiprocess.io/blog/2021-12-16-sqlserver-in-github-actions.html) (blog post)
- 

### Sub-Tasks
- [ ] Create mock API with `/trials` endpoint.
- [ ] Create tests for:
   - [ ] Location with State Parameter (For #84 and #75)
   - [ ] Printing more than 50 trials (For #79 and #77)
   - [ ] "Other Treatment" text (For #76 and #74)
